# Generated by Django 5.1.1 on 2026-08-11 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-month'], 'verbose_name': '月度汇率', 'verbose_name_plural': '月度汇率'},
        ),
        migrations.AlterModelOptions(
            name='operationlog',
            options={'ordering': ['-created_at'], 'verbose_name': '操作日志', 'verbose_name_plural': '操作日志'},
        ),
        migrations.AlterModelOptions(
            name='purchaseassignment',
            options={'verbose_name': '采购供应商归属', 'verbose_name_plural': '采购供应商归属'},
        ),
        migrations.AlterModelOptions(
            name='salesassignment',
            options={'verbose_name': '销售客户归属', 'verbose_name_plural': '销售客户归属'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户日报设置', 'verbose_name_plural': '用户日报设置'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='month',
            field=models.DateField(unique=True, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='usd_to_cny',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='美元兑人民币'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='action',
            field=models.CharField(max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='after_data',
            field=models.JSONField(default=dict, verbose_name='变更后'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='before_data',
            field=models.JSONField(default=dict, verbose_name='变更前'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='model_label',
            field=models.CharField(max_length=120, verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='object_id',
            field=models.CharField(max_length=64, verbose_name='数据编号'),
        ),
        migrations.AlterField(
            model_name='purchaseassignment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='purchaseassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='采购员'),
        ),
        migrations.AlterField(
            model_name='salesassignment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='salesassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='销售业务员'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='供应商名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='首次登录必须改密'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
