# Generated by Django 5.1.1 on 2026-08-22 02:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1300'), help_text='用于「采购销售对比」中把销售额换算成含税金额；0.13 表示 13%。采购金额视为已含税。', max_digits=5, verbose_name='销售增值税率'),
        ),
    ]
