# Generated by Django 5.1.1 on 2026-08-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_sales_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sales_tax_rate',
        ),
    ]
