# Generated by Django 5.1.1 on 2026-08-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereceipt',
            name='amount_cny',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='original_amount',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
