# Generated by Django 5.1.1 on 2026-08-11 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_options_alter_exchangerate_options_and_more'),
        ('purchase', '0002_alter_purchasereceipt_amount_cny_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasereceipt',
            options={'ordering': ['-purchase_date', '-id'], 'verbose_name': '采购日报', 'verbose_name_plural': '采购日报'},
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='amount_cny',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='折算人民币金额'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='采购员'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='currency',
            field=models.CharField(editable=False, max_length=3, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='汇率快照'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='import_batch',
            field=models.UUIDField(blank=True, null=True, verbose_name='导入批次'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='original_amount',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='原币金额'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='purchase_date',
            field=models.DateField(verbose_name='采购日期'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='purchase_type',
            field=models.CharField(choices=[('DOMESTIC', '国内采购'), ('FOREIGN', '国外采购')], max_length=10, verbose_name='采购类型'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='source',
            field=models.CharField(default='MANUAL', max_length=20, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='source_file',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='来源文件'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='来源行号'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
