# Generated by Django 5.1.1 on 2026-08-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchasereceipt_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereceipt',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='数量'),
        ),
    ]
