# Generated by Django 5.1.1 on 2026-08-22 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_company_sales_tax_rate'),
        ('purchase', '0006_alter_purchasereceipt_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['company', '-purchase_date', '-id'], name='pr_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['company', 'buyer', '-purchase_date'], name='pr_company_buyer_idx'),
        ),
    ]
