# Generated by Django 5.1.1 on 2026-10-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_entry_id_entity_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcorrection',
            name='reported_in_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='integrations.reportsnapshot', verbose_name='已报告于快照'),
        ),
    ]
