# Generated by Django 5.1.1 on 2026-08-21 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_company_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='收件组名称')),
                ('scope', models.CharField(choices=[('BOTH', '销售和采购'), ('SALES', '仅销售'), ('PURCHASE', '仅采购')], default='BOTH', max_length=10, verbose_name='推送内容')),
                ('recipients', models.TextField(help_text='多个邮箱用英文逗号或换行分隔。', verbose_name='收件人')),
                ('cc_recipients', models.TextField(blank=True, default='', verbose_name='抄送')),
                ('send_at', models.TimeField(help_text='按服务器所在时区（Asia/Shanghai）触发。', verbose_name='每日发送时间')),
                ('attach_workbook', models.BooleanField(default=True, verbose_name='附带 Excel 明细')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_lists', to='core.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '邮件收件组',
                'verbose_name_plural': '邮件收件组',
                'ordering': ['company', 'send_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='业务日期')),
                ('status', models.CharField(choices=[('SENT', '发送成功'), ('FAILED', '发送失败')], max_length=10, verbose_name='发送结果')),
                ('recipient_count', models.PositiveSmallIntegerField(default=0, verbose_name='收件人数')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='邮件主题')),
                ('message', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.mailinglist', verbose_name='收件组')),
            ],
            options={
                'verbose_name': '邮件发送记录',
                'verbose_name_plural': '邮件发送记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mailinglist',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_mailing_list_per_company'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['mailing_list', 'report_date', 'status'], name='delivery_lookup_idx'),
        ),
    ]
