# Generated by Django 5.1.1 on 2026-08-10 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('DOMESTIC', '内销'), ('EXPORT', '外销')], max_length=10)),
                ('shipment_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('currency', models.CharField(editable=False, max_length=3)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('amount_cny', models.DecimalField(decimal_places=2, max_digits=16)),
                ('source', models.CharField(default='MANUAL', max_length=20)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('import_batch', models.UUIDField(blank=True, null=True)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_shipments',
                'ordering': ['-shipment_date', '-id'],
            },
        ),
    ]
