# Generated by Django 5.1.1 on 2026-08-11 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_options_alter_exchangerate_options_and_more'),
        ('sales', '0002_alter_salesshipment_amount_cny_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesshipment',
            options={'ordering': ['-shipment_date', '-id'], 'verbose_name': '销售日报', 'verbose_name_plural': '销售日报'},
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='amount_cny',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='折算人民币金额'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='currency',
            field=models.CharField(editable=False, max_length=3, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='汇率快照'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='import_batch',
            field=models.UUIDField(blank=True, null=True, verbose_name='导入批次'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='original_amount',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='原币金额'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='销售业务员'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='sale_type',
            field=models.CharField(choices=[('DOMESTIC', '内销'), ('EXPORT', '外销')], max_length=10, verbose_name='销售类型'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='shipment_date',
            field=models.DateField(verbose_name='出货日期'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='source',
            field=models.CharField(default='MANUAL', max_length=20, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='source_file',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='来源文件'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='来源行号'),
        ),
        migrations.AlterField(
            model_name='salesshipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
