# Generated by Django 5.1.1 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_salesshipment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesshipment",
            name="source",
            field=models.CharField(
                choices=[("MANUAL", "手工录入"), ("HISTORY_IMPORT", "历史数据导入")],
                default="MANUAL",
                max_length=20,
                verbose_name="数据来源",
            ),
        ),
    ]
