# Generated by Django 5.1.1 on 2026-08-22 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_company_sales_tax_rate'),
        ('sales', '0006_alter_salesshipment_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesshipment',
            index=models.Index(fields=['company', '-shipment_date', '-id'], name='ss_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='salesshipment',
            index=models.Index(fields=['company', 'owner', '-shipment_date'], name='ss_company_owner_idx'),
        ),
    ]
